name: Subtraction-renderprodject

on:
  push:
    branches:
      -  main

jobs:

  Test:
    name: test
    runs-on: ubuntu-latest
    steps:
      -  name: clone the code from get
         uses: actions/checkout@v4
      -  name: install package to run js code
         run: npm install
      -  name: run test case
         run: npm test   
 ### Deploy:
  #  needs: Test
   # name: deploy
   #runs-on: ubuntu-latest
       
   # steps:
   # -  name: clone the code from get
    #   uses: actions/checkout@v4

    #-  name: Deploy to production
    #   env:
     #     RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      #    RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
      # run: | 
       #   curl -X POST \
        #  -H "Authorization: Bearer $RENDER_API_KEY" \
         # -H "Content-Type: application/json" \
         # -d '{"serviceId": "'$RENDER_SERVICE_ID'"}' \
         # https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys